version: "3.9"
services:
  dnscollector:
    image: ghcr.io/cern-cert/pdnssoc:edge
    command: >
      bash -c "mkdir -p /var/dnscollector/alerts
      && mkdir -p /var/dnscollector/matches
      && pdnssoc-cli -c /etc/pdnssoccli.yml fetch-iocs
      && /usr/bin/supervisord -c /etc/supervisor/supervisord.conf"
    ports:
      - "6000:6000"
    volumes:
      - ./logs:/var/dnscollector/ # Logging destination
      - ./pdnssoccli.yml:/etc/pdnssoccli.yml

  # Uncomment to enable shipping to different logging systems
  # e.g. Opensearch, kafka
  #fluentd:
  #  build: ./fluentd
  #  volumes:
  #    - ./fluentd:/fluentd/etc
  #    - ./logs:/var/pDNSSOC/

